# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        verbose: true
    -   id: end-of-file-fixer
        verbose: true
    -   id: check-added-large-files
        verbose: true
    -   id: check-yaml
        verbose: true
    -   id: flake8
        verbose: true
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    -   id: isort
-   repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
      - id: nbstripout
        name: Clean Jupyter Notebooks
