image: python:3.8

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  steps:
  - step: &release
      name: Creates a release (increment version, add tag, commit and push)
      script:
      - git config --global user.email "$GIT_RELEASE_BOT_EMAIL"
      - git config --global user.name "$GIT_RELEASE_BOT_NAME"
      - git remote set-url origin https://$GIT_ACCOUNT_USER:$GIT_ACCOUNT_PASS@bitbucket.org/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG.git
      - pip install python-semantic-release
      - semantic-release version
      - git push --tags
      - git push
  - step: &publish
      name: Creates a distribution of the package and uploads to our PyPI server
      script:
      - pip install twine
      - python setup.py sdist
      - twine upload --repository-url https://$PYPI_URL --username $PYPI_USER --password
        $PYPI_PASSWORD dist/*
{%- if cookiecutter.automated_testing|lower == 'tox' %}
  - step: &tox
{%- else %}
  - step: &nox
{%- endif %}
      name: Automated tests and code checking
      script:
{%- if cookiecutter.automated_testing|lower == 'tox' %}
      - pip install tox
      - tox
{%- else %}
      - pip install nox
      - nox
{%- endif %}
  - step: &build-sonarcloud
      name: Run tests coverage and Build/test/analyze on SonarCloud
      script:
{%- if cookiecutter.automated_testing|lower == 'tox' %}
      - pip install tox
      - tox -e coverage
{%- else %}
      - pip install nox
      - nox -s coverage
{%- endif %}
      - pipe: sonarsource/sonarcloud-scan:1.0.1
      - pipe: sonarsource/sonarcloud-quality-gate:0.1.3

pipelines:
  branches:
    develop:
      - step: *publish
    master:
      - step: *build-sonarcloud
      - step: *release
  pull-requests:
    '**':
    - step: *build-sonarcloud
{%- if cookiecutter.automated_testing|lower == 'tox' %}
    - step: *tox
{%- else %}
    - step: *nox
{%- endif %}
  tags:
    v*.*.*:
    - step: *publish
